# Site settings
title: СК "ПРОФИДЕНТ" | Стоматология
description: "Стоматологическая клиника в Москве."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: СК "ПРОФИДЕНТ"
    hero_description: Клиника, которой доверяют.

# Contact form
api_token: bb94680964290ea3860d066d637d49ce

# Contact info
contact:
    phone: + 7 909 164 29 15
    # emergency: 931 53 234
    email: profident79@mail.ru
    address: г. Москва, ул. Святоозёрская, д. 14, помещение 12

# Opening hours
monday_friday: 10:00 – 20:00
saturday: 10:00 – 17:00
sunday: Выходной

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
# map:
#     zoom: 17
#     address: г. Москва, ул. Святоозёрская, д. 14, помещение 12
#     address_details: svg/min/logo.svg

# Social settings
facebook: https://www.facebook.com/profile.php?id=100036746894588
twitter: http://twitter.com
instagram: https://www.instagram.com/prfident/
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2019 СК "ПРОФИДЕНТ"

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
